name: Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      # Backend setup
      - name: Setup environment variables for backend
        run: |
          echo "NODE_ENV=development" >> backend/.env.dev
          echo "SERVER_PORT=${{secrets.SERVER_PORT}}" >> backend/.env.dev
          echo "MONGODB_URL=${{secrets.MONGODB_URL}}" >> backend/.env.dev
          echo "FRONTEND_DOMAIN=${{secrets.FRONTEND_URL}}" >> backend/.env.dev
          echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> backend/.env.dev
          echo "JWT_MAX_AGE=${{secrets.JWT_MAX_AGE}}" >> backend/.env.dev
          echo "BCRYPT_SALT_ROUNDS=${{secrets.BCRYPT_SALT_ROUNDS}}" >> backend/.env.dev
          echo "MAIL_SERVICE=${{secrets.MAIL_SERVICE}}" >> backend/.env.dev
          echo "MAIL_HOST=${{secrets.MAIL_HOST}}" >> backend/.env.dev
          echo "MAIL_PORT=${{secrets.MAIL_PORT}}" >> backend/.env.dev
          echo "MAIL_SECURE=${{secrets.MAIL_SECURE}}" >> backend/.env.dev
          echo "MAIL_PASS=${{secrets.MAIL_PASS}}" >> backend/.env.dev
          echo "MAIL_USER=${{secrets.MAIL_USER}}" >> backend/.env.dev
          echo "CRYPTO_SECRET=${{secrets.CRYPTO_SECRET}}" >> backend/.env.dev
          echo "CRYPTO_SECRET_IV=${{secrets.CRYPTO_SECRET_IV}}" >> backend/.env.dev


      - name: Start backend server
        run: |
          cd backend
          npm install
          npm start &
        env:
          NODE_ENV: development

      # Frontend setup
      - name: Setup environment variables for backend
        run: |
          echo "VITE_MAIN_API_URL=${{secrets.BACKEND_URL}}" >> backend/.env
      - name: Start frontend (Vite)
        run: npm run dev &
        env:
          CI: true

      - name: Wait for backend to be ready
        run: npx wait-on http://localhost:1337

      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:5173

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CI: true

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
