name: Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Backend setup
      - name: Setup environment variables for backend
        run: |
          echo "NODE_ENV=development" >> backend/.env.dev
          echo "SERVER_PORT=${{secrets.SERVER_PORT}}" >> backend/.env.dev
          echo "MONGODB_URL=${{secrets.MONGODB_URL}}" >> backend/.env.dev
          echo "FRONTEND_DOMAIN=${{secrets.FRONTEND_URL}}" >> backend/.env.dev
          echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> backend/.env.dev
          echo "JWT_MAX_AGE=${{secrets.JWT_MAX_AGE}}" >> backend/.env.dev
          echo "BCRYPT_SALT_ROUNDS=${{secrets.BCRYPT_SALT_ROUNDS}}" >> backend/.env.dev
          echo "MAIL_SERVICE=${{secrets.MAIL_SERVICE}}" >> backend/.env.dev
          echo "MAIL_HOST=${{secrets.MAIL_HOST}}" >> backend/.env.dev
          echo "MAIL_PORT=${{secrets.MAIL_PORT}}" >> backend/.env.dev
          echo "MAIL_SECURE=${{secrets.MAIL_SECURE}}" >> backend/.env.dev
          echo "MAIL_PASS=${{secrets.MAIL_PASS}}" >> backend/.env.dev
          echo "MAIL_USER=${{secrets.MAIL_USER}}" >> backend/.env.dev
          echo "CRYPTO_SECRET=${{secrets.CRYPTO_SECRET}}" >> backend/.env.dev
          echo "CRYPTO_SECRET_IV=${{secrets.CRYPTO_SECRET_IV}}" >> backend/.env.dev


      - name: Start backend server
        run: |
          cd backend
          npm install
          node app.js -- --host 0.0.0.0 &
        env:
          NODE_ENV: development

      # Step 4: Start Vite application from the frontend folder
      - name: Start Vite application
        run: |
          cd frontend
          npm install
          npm run dev -- --host 0.0.0.0 &

      # Step 5: Wait for Vite to be ready
      - name: Wait for Vite to be ready
        run: npx wait-on http://localhost:5173

      # Step 6: Run Cypress tests
      - name: Run Cypress tests
        run: |
          cd frontend
          npx cypress run --browser chrome --headless

