name: Cypress E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Backend setup
      - name: Setup environment variables for backend
        working-directory: backend
        run: |
          echo "NODE_ENV=development" >> .env.dev
          echo "API_PORT=3000" >> .env.dev
          echo "MONGODB_URL=${{secrets.MONGODB_URL}}" >> .env.dev
          echo "FRONTEND_DOMAIN='http://localhost:5173'" >> .env.dev
          echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> .env.dev
          echo "JWT_MAX_AGE=${{secrets.JWT_MAX_AGE}}" >> .env.dev
          echo "BCRYPT_SALT_ROUNDS=${{secrets.BCRYPT_SALT_ROUNDS}}" >> .env.dev
          echo "MAIL_SERVICE=${{secrets.MAIL_SERVICE}}" >> .env.dev
          echo "MAIL_HOST=${{secrets.MAIL_HOST}}" >> .env.dev
          echo "MAIL_PORT=${{secrets.MAIL_PORT}}" >> .env.dev
          echo "MAIL_SECURE=${{secrets.MAIL_SECURE}}" >> .env.dev
          echo "MAIL_PASS=${{secrets.MAIL_PASS}}" >> .env.dev
          echo "MAIL_USER=${{secrets.MAIL_USER}}" >> .env.dev
          echo "CRYPTO_SECRET=${{secrets.CRYPTO_SECRET}}" >> .env.dev
          echo "CRYPTO_SECRET_IV=${{secrets.CRYPTO_SECRET_IV}}" >> .env.dev
          echo "ALLOWED_ORIGINS=${{secrets.ALLOWED_ORIGINS}}" >> .env.dev


      - name: Start backend server
        working-directory: backend
        run: |
          npm install
          node src/app.js -- --host 0.0.0.0 &
          sleep 10 # Wait for backend to start up
        env:
          NODE_ENV: development

      # Step 4: Start Vite application from the frontend folder
      - name: Start Vite application
        working-directory: frontend
        run: |
          echo "VITE_MAIN_API_URL = 'http://localhost:3000/api'" >> .env
          npm install
          npm run dev -- --host 0.0.0.0 &

      # Step 5: Wait for Vite and API to be ready
      - name: Wait for Vite to be ready
        run: npx wait-on http://localhost:5173/ --timeout 60000

      # Step 6: Run Cypress tests
      - name: Run Cypress tests
        working-directory: frontend
        run: npx cypress run
